In [83]:
import numpy as np
import pandas as pd

In [84]:
df = pd.read_csv("../Dataset/athlete_events.csv")
region_df = pd.read_csv("../Dataset/noc_regions.csv")

In [85]:
df.sample(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
62143,31823,Simon Ekeno,M,26.0,178.0,58.0,Kenya,KEN,1972 Summer,1972,Summer,Munich,Shooting,"Shooting Mixed Small-Bore Rifle, Prone, 50 metres",NaN
180276,90600,Edgardo Pailos Rugna,M,24.0,180.0,79.0,Argentina,ARG,1992 Summer,1992,Summer,Barcelona,Hockey,Hockey Men's Hockey,NaN
257020,128697,Ratu Tevita Waranaivalu,M,20.0,172.0,72.0,Fiji,FIJ,2016 Summer,2016,Summer,Rio de Janeiro,Football,Football Men's Football,NaN
39521,20335,Chen Zhong,F,25.0,183.0,73.0,China,CHN,2008 Summer,2008,Summer,Beijing,Taekwondo,Taekwondo Women's Heavyweight,NaN
100511,50829,Nicolas Huet,M,29.0,184.0,85.0,France,FRA,2006 Winter,2006,Winter,Torino,Snowboarding,Snowboarding Men's Parallel Giant Slalom,NaN

In [86]:
region_df.sample(5)

     NOC      region notes
91   INA   Indonesia   NaN
14   AZE  Azerbaijan   NaN
122  LUX  Luxembourg   NaN
65   ETH    Ethiopia   NaN
189  SUD       Sudan   NaN

In [87]:
df.shape

(271116, 15)

In [88]:
# Here we are consodering only the summer olympics
df = df[df['Season'] == 'Summer']
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN

In [89]:
df.shape

(222552, 15)

In [90]:
df = df.merge(region_df, how='left', on='NOC')
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN

In [91]:
# Total number of countries participated
print(df['region'].unique())
print(len(df['region'].unique()))

['China' 'Denmark' 'Netherlands' 'Finland' 'Norway' 'Romania' 'Estonia'
 'France' 'Morocco' 'Spain' 'Egypt' 'Iran' 'Bulgaria' 'Italy' 'Chad'
 'Azerbaijan' 'Sudan' 'Russia' 'Argentina' 'Cuba' 'Belarus' 'Greece'
 'Cameroon' 'Turkey' 'Chile' 'Mexico' 'USA' 'Nicaragua' 'Hungary'
 'Nigeria' 'Algeria' 'Kuwait' 'Bahrain' 'Pakistan' 'Iraq' 'Syria'
 'Lebanon' 'Qatar' 'Malaysia' 'Germany' 'Canada' 'Ireland' 'Australia'
 'South Africa' 'Eritrea' 'Tanzania' 'Jordan' 'Tunisia' 'Libya' 'Belgium'
 'Djibouti' 'Palestine' 'Comoros' 'Kazakhstan' 'Brunei' 'India'
 'Saudi Arabia' 'Maldives' 'Ethiopia' 'United Arab Emirates' 'Yemen'
 'Indonesia' 'Philippines' nan 'Uzbekistan' 'Kyrgyzstan' 'Tajikistan'
 'Japan' 'Republic of Congo' 'Switzerland' 'Brazil' 'Monaco' 'Israel'
 'Uruguay' 'Sweden' 'Sri Lanka' 'Armenia' 'Ivory Coast' 'Kenya' 'Benin'
 'UK' 'Ghana' 'Somalia' 'Niger' 'Mali' 'Afghanistan' 'Poland' 'Costa Rica'
 'Panama' 'Georgia' 'Slovenia' 'Guyana' 'New Zealand' 'Portugal'
 'Paraguay' 'Angola' 'Venezuela' 'Colombia' 'Bangladesh' 'Peru'
 'El Salvador' 'Puerto Rico' 'Uganda' 'Honduras' 'Ecuador' 'Turkmenistan'
 'Mauritius' 'Seychelles' 'Czech Republic' 'Luxembourg' 'Mauritania'
 'Saint Kitts' 'Trinidad' 'Dominican Republic' 'Saint Vincent' 'Jamaica'
 'Liberia' 'Suriname' 'Nepal' 'Mongolia' 'Austria' 'Palau' 'Lithuania'
 'Togo' 'Namibia' 'Curacao' 'Ukraine' 'Iceland' 'American Samoa' 'Samoa'
 'Rwanda' 'Croatia' 'Dominica' 'Haiti' 'Malta' 'Cyprus' 'Guinea' 'Belize'
 'Thailand' 'Bermuda' 'Serbia' 'Sierra Leone' 'Papua New Guinea'
 'Individual Olympic Athletes' 'Oman' 'Fiji' 'Vanuatu' 'Moldova' 'Bahamas'
 'Guatemala' 'Latvia' 'Virgin Islands, British' 'Mozambique'
 'Virgin Islands, US' 'Central African Republic' 'Madagascar'
 'Bosnia and Herzegovina' 'Guam' 'Cayman Islands' 'Slovakia' 'Barbados'
 'Guinea-Bissau' 'Timor-Leste' 'Democratic Republic of the Congo' 'Gabon'
 'San Marino' 'Laos' 'Botswana' 'South Korea' 'Cambodia' 'North Korea'
 'Solomon Islands' 'Senegal' 'Cape Verde' 'Equatorial Guinea' 'Boliva'
 'Antigua' 'Andorra' 'Zimbabwe' 'Grenada' 'Saint Lucia' 'Micronesia'
 'Myanmar' 'Malawi' 'Zambia' 'Taiwan' 'Sao Tome and Principe' 'Macedonia'
 'Liechtenstein' 'Montenegro' 'Gambia' 'Cook Islands' 'Albania'
 'Swaziland' 'Burkina Faso' 'Burundi' 'Aruba' 'Nauru' 'Vietnam' 'Bhutan'
 'Marshall Islands' 'Kiribati' 'Tonga' 'Kosovo' 'South Sudan' 'Lesotho']
206

In [92]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9189
Height     51857
Weight     53854
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     188464
region       370
notes     218151
dtype: int64

there are some region , which is not associated with any NOC

In [93]:
df.duplicated().sum()

1385

In [94]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

0

There are many NAN in the medal, so we cant remove it bcz there are countries without medal win. But we doing OHE for each cat

In [95]:
df = pd.concat([df, pd.get_dummies(df['Medal']).astype(int)],
               axis=1)  # we apply .astype(int) to convert boolean to int
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,0,0,0
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,0,0,0
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,0,0,0
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,0,1,0
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,0,0,0

In [96]:
df.groupby("NOC").sum()[['Bronze', 'Gold', 'Silver']
                        ].sort_values("Gold", ascending=False).reset_index()

     NOC  Bronze  Gold  Silver
0    USA    1197  2472    1333
1    URS     596   832     635
2    GBR     620   635     729
3    GER     649   592     538
4    ITA     454   518     474
..   ...     ...   ...     ...
225  AHO       0     0       1
226  LBR       0     0       0
227  LCA       0     0       0
228  LES       0     0       0
229  LBA       0     0       0

[230 rows x 4 columns]

In the data, if any team won gold medal as a team then here its showing 1 gold medal for each player, instead of 1.
So here need to fix it

In [97]:
df[(df["NOC"] == "IND") & (df["Medal"] == "Gold")]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
4186,2699,Shaukat Ali,M,30.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4190,2703,Syed Mushtaq Ali,M,22.0,165.0,61.0,India,IND,1964 Summer,1964,Summer,Tokyo,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4460,2864,Richard James Allen,M,25.0,172.0,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4461,2864,Richard James Allen,M,30.0,172.0,NaN,India,IND,1932 Summer,1932,Summer,Los Angeles,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4462,2864,Richard James Allen,M,34.0,172.0,NaN,India,IND,1936 Summer,1936,Summer,Berlin,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191759,117232,Dung Dung Sylvanus,M,31.0,160.0,62.0,India,IND,1980 Summer,1980,Summer,Moskva,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
193964,118553,Carlyle Carrol Tapsell,M,23.0,182.0,NaN,India,IND,1932 Summer,1932,Summer,Los Angeles,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
193965,118553,Carlyle Carrol Tapsell,M,27.0,182.0,NaN,India,IND,1936 Summer,1936,Summer,Berlin,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
205949,125560,"Max ""Maxie"" Vaz",M,NaN,NaN,NaN,India,IND,1948 Summer,1948,Summer,London,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
219336,133554,Sayed Muhammad Yusuf,M,NaN,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0

Here we can see in the same year same game multiple gold medal, bcz it is showing individual per person.
So we need to remove duplicate base on Year, NOC, Games, Year, Season, City

Medal tally Analysis

In [98]:
medal_telly = df.drop_duplicates(subset=['Team', "NOC", "Games", "Year",
                                         "City", "Sport", "Event", "Medal"])
medal_telly

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,0,0,0
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,0,0,0
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,0,0,0
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,0,1,0
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222528,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956 Summer,1956,Summer,Melbourne,Athletics,Athletics Women's Shot Put,Silver,Russia,NaN,0,0,1
222530,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964 Summer,1964,Summer,Tokyo,Athletics,Athletics Women's Shot Put,Bronze,Russia,NaN,1,0,0
222536,135556,Bogusaw Stanisaw Zychowicz,M,19.0,189.0,80.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Swimming,Swimming Men's 100 metres Butterfly,NaN,Poland,NaN,0,0,0
222537,135556,Bogusaw Stanisaw Zychowicz,M,19.0,189.0,80.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Swimming,Swimming Men's 200 metres Butterfly,NaN,Poland,NaN,0,0,0
222541,135560,Stavroula Zygouri,F,36.0,171.0,63.0,Greece,GRE,2004 Summer,2004,Summer,Athina,Wrestling,"Wrestling Women's Middleweight, Freestyle",NaN,Greece,NaN,0,0,0

In [99]:
medal_telly = medal_telly.groupby("NOC").sum()[['Bronze', 'Silver', 'Gold']
                                               ].sort_values("Gold", ascending=False).reset_index()

In [100]:
medal_telly["total"] = medal_telly["Bronze"] + \
    medal_telly["Silver"] + medal_telly["Gold"]
medal_telly

     NOC  Bronze  Silver  Gold  total
0    USA     708     802  1035   2545
1    URS     294     317   394   1005
2    GBR     300     317   278    895
3    GER     283     261   235    779
4    FRA     287     256   234    777
..   ...     ...     ...   ...    ...
225  AHO       0       1     0      1
226  LBR       0       0     0      0
227  LCA       0       0     0      0
228  LES       0       0     0      0
229  LBA       0       0     0      0

[230 rows x 5 columns]

Getting year to show in the filter tab

In [105]:
year = df["Year"].unique().tolist()
year.sort()
year.insert(0, "Overall")
year

['Overall',
 1896,
 1900,
 1904,
 1906,
 1908,
 1912,
 1920,
 1924,
 1928,
 1932,
 1936,
 1948,
 1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016]

Getting Country to show in the filter tab

In [107]:
# Here county consist of NaN values as well, so we cant directly sort it
# need to remove NaN values first

county = np.unique(df["region"].dropna().values).tolist()
county.sort()
county.insert(0, "Overall")
county

['Overall',
 'Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Boliva',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Cook Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Individual Olympic Athletes',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Republic of Congo',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts',
 'Saint Lucia',
 'Saint Vincent',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'UK',
 'USA',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Virgin Islands, British',
 'Virgin Islands, US',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [111]:
def fetch_medal_tally(df, year, county):
    df = df.drop_duplicates(subset=['Team', "NOC", "Games", "Year",
                                    "City", "Sport", "Event", "Medal"])

    flag = 0
    if year == "Overall" and county == "Overall":
        temp_df = df
    elif year == "Overall" and county != "Overall":
        flag = 1
        temp_df = df[df["region"] == county]
    elif year != "Overall" and county == "Overall":
        temp_df = df[df["Year"] == int(year)]
    elif year != "Overall" and county != "Overall":
        temp_df = df[(df["Year"] == int(year)) & (df["region"] == county)]

    if flag == 1:
        temp_df = temp_df.groupby("Year").sum()[['Bronze', 'Silver', 'Gold']
                                                ].sort_values("Year", ascending=True).reset_index()
    else:
        temp_df = temp_df.groupby("region").sum()[['Bronze', 'Silver', 'Gold']
                                                  ].sort_values("Gold", ascending=False).reset_index()

    temp_df["total"] = temp_df["Bronze"] + \
        temp_df["Silver"] + temp_df["Gold"]

    return temp_df


fetch_medal_tally(df, year="2012", county="India")

  region  Bronze  Silver  Gold  total
0  India       4       2     0      6

Overall Analysis