In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("../Dataset/athlete_events.csv")
region_df = pd.read_csv("../Dataset/noc_regions.csv")

In [ ]:
df.sample(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
166698,83731,"Saara Johanna ""Sara"" Mustonen",F,35.0,161.0,58.0,Sweden,SWE,2016 Summer,2016,Summer,Rio de Janeiro,Cycling,"Cycling Women's Road Race, Individual",NaN
137934,69321,Li Chun-Mi,F,15.0,NaN,NaN,North Korea,PRK,1992 Summer,1992,Summer,Barcelona,Gymnastics,Gymnastics Women's Horse Vault,NaN
247456,123886,Csar Valds Lpez,M,26.0,186.0,87.0,Cuba,CUB,1968 Summer,1968,Summer,Mexico City,Basketball,Basketball Men's Basketball,NaN
189838,95350,Cdric Planon,M,27.0,180.0,88.0,France,FRA,1996 Summer,1996,Summer,Atlanta,Weightlifting,Weightlifting Men's Middle-Heavyweight,NaN
82040,41657,Valentn Gonzlez Avila,M,26.0,NaN,NaN,Mexico,MEX,1936 Summer,1936,Summer,Berlin,Athletics,"Athletics Men's 5,000 metres",NaN

In [ ]:
region_df.sample(5)

     NOC           region notes
163  POR         Portugal   NaN
74   GBR               UK   NaN
183  SOL  Solomon Islands   NaN
14   AZE       Azerbaijan   NaN
54   CZE   Czech Republic   NaN

In [ ]:
df.shape

(271116, 15)

In [ ]:
# Here we are consodering only the summer olympics
df = df[df['Season'] == 'Summer']
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN

In [ ]:
df.shape

(222552, 15)

In [ ]:
df = df.merge(region_df, how='left', on='NOC')
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN

In [ ]:
# Total number of countries participated
print(df['region'].unique())
print(len(df['region'].unique()))

['China' 'Denmark' 'Netherlands' 'Finland' 'Norway' 'Romania' 'Estonia'
 'France' 'Morocco' 'Spain' 'Egypt' 'Iran' 'Bulgaria' 'Italy' 'Chad'
 'Azerbaijan' 'Sudan' 'Russia' 'Argentina' 'Cuba' 'Belarus' 'Greece'
 'Cameroon' 'Turkey' 'Chile' 'Mexico' 'USA' 'Nicaragua' 'Hungary'
 'Nigeria' 'Algeria' 'Kuwait' 'Bahrain' 'Pakistan' 'Iraq' 'Syria'
 'Lebanon' 'Qatar' 'Malaysia' 'Germany' 'Canada' 'Ireland' 'Australia'
 'South Africa' 'Eritrea' 'Tanzania' 'Jordan' 'Tunisia' 'Libya' 'Belgium'
 'Djibouti' 'Palestine' 'Comoros' 'Kazakhstan' 'Brunei' 'India'
 'Saudi Arabia' 'Maldives' 'Ethiopia' 'United Arab Emirates' 'Yemen'
 'Indonesia' 'Philippines' nan 'Uzbekistan' 'Kyrgyzstan' 'Tajikistan'
 'Japan' 'Republic of Congo' 'Switzerland' 'Brazil' 'Monaco' 'Israel'
 'Uruguay' 'Sweden' 'Sri Lanka' 'Armenia' 'Ivory Coast' 'Kenya' 'Benin'
 'UK' 'Ghana' 'Somalia' 'Niger' 'Mali' 'Afghanistan' 'Poland' 'Costa Rica'
 'Panama' 'Georgia' 'Slovenia' 'Guyana' 'New Zealand' 'Portugal'
 'Paraguay' 'Angola' 'Venezuela' 'Colombia' 'Bangladesh' 'Peru'
 'El Salvador' 'Puerto Rico' 'Uganda' 'Honduras' 'Ecuador' 'Turkmenistan'
 'Mauritius' 'Seychelles' 'Czech Republic' 'Luxembourg' 'Mauritania'
 'Saint Kitts' 'Trinidad' 'Dominican Republic' 'Saint Vincent' 'Jamaica'
 'Liberia' 'Suriname' 'Nepal' 'Mongolia' 'Austria' 'Palau' 'Lithuania'
 'Togo' 'Namibia' 'Curacao' 'Ukraine' 'Iceland' 'American Samoa' 'Samoa'
 'Rwanda' 'Croatia' 'Dominica' 'Haiti' 'Malta' 'Cyprus' 'Guinea' 'Belize'
 'Thailand' 'Bermuda' 'Serbia' 'Sierra Leone' 'Papua New Guinea'
 'Individual Olympic Athletes' 'Oman' 'Fiji' 'Vanuatu' 'Moldova' 'Bahamas'
 'Guatemala' 'Latvia' 'Virgin Islands, British' 'Mozambique'
 'Virgin Islands, US' 'Central African Republic' 'Madagascar'
 'Bosnia and Herzegovina' 'Guam' 'Cayman Islands' 'Slovakia' 'Barbados'
 'Guinea-Bissau' 'Timor-Leste' 'Democratic Republic of the Congo' 'Gabon'
 'San Marino' 'Laos' 'Botswana' 'South Korea' 'Cambodia' 'North Korea'
 'Solomon Islands' 'Senegal' 'Cape Verde' 'Equatorial Guinea' 'Boliva'
 'Antigua' 'Andorra' 'Zimbabwe' 'Grenada' 'Saint Lucia' 'Micronesia'
 'Myanmar' 'Malawi' 'Zambia' 'Taiwan' 'Sao Tome and Principe' 'Macedonia'
 'Liechtenstein' 'Montenegro' 'Gambia' 'Cook Islands' 'Albania'
 'Swaziland' 'Burkina Faso' 'Burundi' 'Aruba' 'Nauru' 'Vietnam' 'Bhutan'
 'Marshall Islands' 'Kiribati' 'Tonga' 'Kosovo' 'South Sudan' 'Lesotho']
206

In [ ]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9189
Height     51857
Weight     53854
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     188464
region       370
notes     218151
dtype: int64

there are some region , which is not associated with any NOC

In [ ]:
df.duplicated().sum()

1385

In [ ]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

0

There are many NAN in the medal, so we cant remove it bcz there are countries without medal win. But we doing OHE for each cat

In [ ]:
df = pd.concat([df, pd.get_dummies(df['Medal']).astype(int)],
               axis=1)  # we apply .astype(int) to convert boolean to int
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,0,0,0
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,0,0,0
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,0,0,0
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,0,1,0
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,0,0,0

In [ ]:
df.groupby("NOC").sum()[['Bronze', 'Gold', 'Silver']
                        ].sort_values("Gold", ascending=False).reset_index()

     NOC  Bronze  Gold  Silver
0    USA    1197  2472    1333
1    URS     596   832     635
2    GBR     620   635     729
3    GER     649   592     538
4    ITA     454   518     474
..   ...     ...   ...     ...
225  AHO       0     0       1
226  LBR       0     0       0
227  LCA       0     0       0
228  LES       0     0       0
229  LBA       0     0       0

[230 rows x 4 columns]

In the data, if any team won gold medal as a team then here its showing 1 gold medal for each player, instead of 1.
So here need to fix it

In [ ]:
df[(df["NOC"] == "IND") & (df["Medal"] == "Gold")]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
4186,2699,Shaukat Ali,M,30.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4190,2703,Syed Mushtaq Ali,M,22.0,165.0,61.0,India,IND,1964 Summer,1964,Summer,Tokyo,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4460,2864,Richard James Allen,M,25.0,172.0,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4461,2864,Richard James Allen,M,30.0,172.0,NaN,India,IND,1932 Summer,1932,Summer,Los Angeles,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4462,2864,Richard James Allen,M,34.0,172.0,NaN,India,IND,1936 Summer,1936,Summer,Berlin,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191759,117232,Dung Dung Sylvanus,M,31.0,160.0,62.0,India,IND,1980 Summer,1980,Summer,Moskva,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
193964,118553,Carlyle Carrol Tapsell,M,23.0,182.0,NaN,India,IND,1932 Summer,1932,Summer,Los Angeles,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
193965,118553,Carlyle Carrol Tapsell,M,27.0,182.0,NaN,India,IND,1936 Summer,1936,Summer,Berlin,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
205949,125560,"Max ""Maxie"" Vaz",M,NaN,NaN,NaN,India,IND,1948 Summer,1948,Summer,London,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
219336,133554,Sayed Muhammad Yusuf,M,NaN,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0

Here we can see in the same year same game multiple gold medal, bcz it is showing individual per person.
So we need to remove duplicate base on Year, NOC, Games, Year, Season, City

In [ ]:
medal_telly = df.drop_duplicates(subset=['Team', "NOC", "Games", "Year",
                                         "City", "Sport", "Event", "Medal"])
medal_telly

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,0,0,0
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,0,0,0
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,0,0,0
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,0,1,0
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222528,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956 Summer,1956,Summer,Melbourne,Athletics,Athletics Women's Shot Put,Silver,Russia,NaN,0,0,1
222530,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964 Summer,1964,Summer,Tokyo,Athletics,Athletics Women's Shot Put,Bronze,Russia,NaN,1,0,0
222536,135556,Bogusaw Stanisaw Zychowicz,M,19.0,189.0,80.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Swimming,Swimming Men's 100 metres Butterfly,NaN,Poland,NaN,0,0,0
222537,135556,Bogusaw Stanisaw Zychowicz,M,19.0,189.0,80.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Swimming,Swimming Men's 200 metres Butterfly,NaN,Poland,NaN,0,0,0
222541,135560,Stavroula Zygouri,F,36.0,171.0,63.0,Greece,GRE,2004 Summer,2004,Summer,Athina,Wrestling,"Wrestling Women's Middleweight, Freestyle",NaN,Greece,NaN,0,0,0

In [ ]:
medal_telly = medal_telly.groupby("NOC").sum()[['Bronze', 'Silver', 'Gold']
                                               ].sort_values("Gold", ascending=False).reset_index()

     NOC  Bronze  Silver  Gold
0    USA     708     802  1035
1    URS     294     317   394
2    GBR     300     317   278
3    GER     283     261   235
4    FRA     287     256   234
..   ...     ...     ...   ...
225  AHO       0       1     0
226  LBR       0       0     0
227  LCA       0       0     0
228  LES       0       0     0
229  LBA       0       0     0

[230 rows x 4 columns]

In [ ]:
medal_telly["total"] = medal_telly["Bronze"] + \
    medal_telly["Silver"] + medal_telly["Gold"]
medal_telly

C:\Users\ASUS\AppData\Local\Temp\ipykernel_2544\1354698409.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medal_telly["total"] = medal_telly["Bronze"] + \

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,...,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver,total
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,...,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,0,0,0,0
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,...,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,0,0,0,0
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,...,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,0,0,0,0
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,...,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,0,1,0,1
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,...,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222528,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956 Summer,1956,...,Melbourne,Athletics,Athletics Women's Shot Put,Silver,Russia,NaN,0,0,1,1
222530,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964 Summer,1964,...,Tokyo,Athletics,Athletics Women's Shot Put,Bronze,Russia,NaN,1,0,0,1
222536,135556,Bogusaw Stanisaw Zychowicz,M,19.0,189.0,80.0,Poland,POL,1980 Summer,1980,...,Moskva,Swimming,Swimming Men's 100 metres Butterfly,NaN,Poland,NaN,0,0,0,0
222537,135556,Bogusaw Stanisaw Zychowicz,M,19.0,189.0,80.0,Poland,POL,1980 Summer,1980,...,Moskva,Swimming,Swimming Men's 200 metres Butterfly,NaN,Poland,NaN,0,0,0,0
222541,135560,Stavroula Zygouri,F,36.0,171.0,63.0,Greece,GRE,2004 Summer,2004,...,Athina,Wrestling,"Wrestling Women's Middleweight, Freestyle",NaN,Greece,NaN,0,0,0,0